// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/k8s-pod-status/pkg"
	v1 "k8s.io/api/core/v1"
)

type PodStatusMetrics struct {
	RemoveStub        func(v1.Pod)
	removeMutex       sync.RWMutex
	removeArgsForCall []struct {
		arg1 v1.Pod
	}
	SetStub        func(v1.Pod)
	setMutex       sync.RWMutex
	setArgsForCall []struct {
		arg1 v1.Pod
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PodStatusMetrics) Remove(arg1 v1.Pod) {
	fake.removeMutex.Lock()
	fake.removeArgsForCall = append(fake.removeArgsForCall, struct {
		arg1 v1.Pod
	}{arg1})
	stub := fake.RemoveStub
	fake.recordInvocation("Remove", []interface{}{arg1})
	fake.removeMutex.Unlock()
	if stub != nil {
		fake.RemoveStub(arg1)
	}
}

func (fake *PodStatusMetrics) RemoveCallCount() int {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	return len(fake.removeArgsForCall)
}

func (fake *PodStatusMetrics) RemoveCalls(stub func(v1.Pod)) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = stub
}

func (fake *PodStatusMetrics) RemoveArgsForCall(i int) v1.Pod {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	argsForCall := fake.removeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PodStatusMetrics) Set(arg1 v1.Pod) {
	fake.setMutex.Lock()
	fake.setArgsForCall = append(fake.setArgsForCall, struct {
		arg1 v1.Pod
	}{arg1})
	stub := fake.SetStub
	fake.recordInvocation("Set", []interface{}{arg1})
	fake.setMutex.Unlock()
	if stub != nil {
		fake.SetStub(arg1)
	}
}

func (fake *PodStatusMetrics) SetCallCount() int {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return len(fake.setArgsForCall)
}

func (fake *PodStatusMetrics) SetCalls(stub func(v1.Pod)) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = stub
}

func (fake *PodStatusMetrics) SetArgsForCall(i int) v1.Pod {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	argsForCall := fake.setArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PodStatusMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PodStatusMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.PodStatusMetrics = new(PodStatusMetrics)
